server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/order/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payment/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: DEBUG
